name: Update Action
run-name: ${{ github.repository }} index update
on: [push]
jobs:
  Update-Index:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This job is automatically triggered by a ${{ github.event_name }} event for branch ${{ github.ref }} in repo ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Run update script
        run: ./update_index.bash
        shell: bash
      - name: Add, commit, and push changes
        run: |
          git config user.name "solcummings"
          git config user.email "78600269+solcummings@users.noreply.github.com"
          git add -A
          git commit -m "Updated index"
          git push
      - run: echo "This job's status is ${{ job.status }}."
